### PR TITLE
Adding my first draft of the OAuth2 Adapter code  to the readme

### PR DESCRIPTION
**Pull request by mfrost503**
First go at this, this is using League OAuth 2.0 client 0.3.0 and dev-master of Aura.Auth - I've written the code and tested it and it works. Just let me know if anything reads weird or any other changes you have, also if I need to make this PR against master (which I just now considered, I can do that too).

### CODE REVIEW

**Comment by harikt** [comment]
Hey @mfrost503 , 

Thank you for the PR . Don't check master . It should come to `develop-2` in this case ( version 2) . There is `develop` also for version 1.

Thanks

**Comment by mfrost503** [comment]
@harikt - Ok I based the code on dev-master assuming that was correct, AdapterInterface has 3 fewer methods on develop-2. So if I need to I can remove the getUser, getInfo and getError methods from the adapter in the example. Just wanted to make sure the example fits for the version it will be included in (though it will still work fine if those empty methods remain, it might be confusing)

**Comment by harikt** [comment]
Somethings I noticed https://github.com/auraphp/Aura.Auth/pull/42/files#diff-04c6e90faac2675aa89e2176d2eec7d8R774

``` php
return ($username, $data);
```

Did you missed to write array?

The second one is https://github.com/auraphp/Aura.Auth/pull/42/files#diff-04c6e90faac2675aa89e2176d2eec7d8R841

``` php
+require_once 'vendor/autoload.php';
+require_once 'vendor/aura/auth/autoload.php';
```

You don't need to call `vendor/aura/auth/autoload.php` for aura will be autoloaded via composer. The autoload is kept for those who are not downloading things via composer.

Eg : git clone .

Could not comment against a diff. Not sure why :( .

**Comment by harikt** [comment]
Looking more, from my understanding, you may not need to create as many adapters for aura.

https://github.com/auraphp/Aura.Auth/pull/42/files#diff-04c6e90faac2675aa89e2176d2eec7d8R726

You may want to create the `LeagueOauth2Adapter` than the `GithubAdapter` . We are providing the provider and the providers can be changed. So naming it as `GithubAdapter` sounds not nice.

By the way have you checked https://github.com/Lusitanian/PHPoAuthLib ? There are a bunch of adapters already. May be @pmjones  mentioned to check league ?

**Comment by mfrost503** [comment]
I agree, it should be named differently, I'll make sure to correct that. And your assumption is correct, Paul and I discussed using the league package. I don't mind either way—

**Comment by harikt** [comment]
Thanks. You can also remove these

``` php
+
+ /**
+ * getUser method required to fulfill contract with AdapterInterface
+ */
+ public function getUser()
+ {
+ // nothing to do here
+ }
+
+ /**
+ * getInfo method required to fulfill contract with AdapterInterface
+ */
+ public function getInfo()
+ {
+ // nothing to do here
+ }
+
+ /**
+ * getError method required to fulfill contract with AdapterInterface
+ */
+ public function getError()
+ {
+ // nothing to do here
+ }
```

As you mentioned no longer used in https://github.com/auraphp/Aura.Auth/blob/develop-2/src/Adapter/AdapterInterface.php

**Comment by harikt** [comment]
The signature also differs a bit .

``` php
public function resume(Auth $auth);
public function login(array $input);
public function logout(Auth $auth);
```

**Comment by harikt** [comment]
``` php
$auraAdapter = new Adapter\LeagueOAuth2Adapter($githubProvider);
```

Please make use of use statement. Else there is a confusion on looking at namespace and example namespace. 

``` php
use OAuth2\Adapter\LeagueOAuth2Adapter;

$auraAdapter = new LeagueOAuth2Adapter($githubProvider);
```

**Comment by harikt** [comment]
One more thing is to make it consistent 

``` php
+use \League\OAuth2\Client\Provider\Github;
+use \Aura\Auth\Exception;
```

may be remove the `\` from the front.

``` php
+use League\OAuth2\Client\Provider\Github;
+use Aura\Auth\Exception;
```

**Comment by harikt** [comment]
Thank you @mfrost503 for the PR. @pmjones will look into this and comment on his thoughts and merge :+1:  .

Have a nice day!

**Comment by mfrost503** [comment]
Added one last thing, which was to make the docblocks reflect the method signature, thanks for your help getting this up to snuff :)
-- 
Matt Frost

On August 25, 2014 at 10:58:52 PM, Hari K T (notifications@github.com) wrote:

Thank you @mfrost503 for the PR. @pmjones will look into this and comment on his thoughts and merge  .

Have a nice day!

**Comment by harikt** [comment]
Your twitter handle is https://twitter.com/shrtwhitebldguy right ?

**Comment by mfrost503** [comment]
Yep—

**Comment by pmjones** [comment]
@mfrost503 -- thanks! Will merge.

@harikt -- good editing, sir!

**Comment by harikt** [comment]
You are welcome :) .

**Pull request merged**
