### PR TITLE
Use more meaningful and useful values.

### PR DESCRIPTION
**Pull request by cxj**
Fixes issue #81.

### CODE REVIEW

**Comment by harikt** [comment]
This commit actually breaks the tests. 

`ini_gc_maxlifetime => ini_get('session.gc_maxlifetime')`

Now the `idle_ttl = 3600`  and default value of `ini_get('session.gc_maxlifetime')`  is 1440 .

So either we need to change here also : https://github.com/auraphp/Aura.Auth/blob/2e531e0477a513d6cecc0551a3875e611856e222/config/Common.php#L102 . 

and may be in the `AuthFactory` https://github.com/auraphp/Aura.Auth/blob/2e531e0477a513d6cecc0551a3875e611856e222/src/AuthFactory.php#L144 ?

Why test fails : https://github.com/auraphp/Aura.Auth/blob/2e531e0477a513d6cecc0551a3875e611856e222/src/Session/Timer.php#L78 . ( 3 failures )

```
1) Aura\Auth\ContainerTest::testGet with data set #3 ('aura/auth:resume_service', 'Aura\Auth\Service\ResumeService')
Aura\Auth\Exception: session.gc_maxlifetime less than idle time
/home/travis/build/auraphp/Aura.Auth/src/Session/Timer.php:97
/home/travis/build/auraphp/Aura.Auth/src/Session/Timer.php:78
/home/travis/build/auraphp/Aura.Auth/vendor/aura/di/src/Reflection.php:74
/home/travis/build/auraphp/Aura.Auth/vendor/aura/di/src/Factory.php:286
/home/travis/build/auraphp/Aura.Auth/vendor/aura/di/src/Factory.php:286
/home/travis/build/auraphp/Aura.Auth/vendor/aura/di/src/InstanceFactory.php:101
/home/travis/build/auraphp/Aura.Auth/vendor/aura/di/src/Factory.php:366
/home/travis/build/auraphp/Aura.Auth/vendor/aura/di/src/Factory.php:269
/home/travis/build/auraphp/Aura.Auth/vendor/aura/di/src/InstanceFactory.php:101
/home/travis/build/auraphp/Aura.Auth/vendor/aura/di/src/Container.php:297
/home/travis/build/auraphp/Aura.Auth/vendor/aura/di/tests/_Config/AbstractContainerTest.php:106
```

https://travis-ci.org/auraphp/Aura.Auth/jobs/249291656#L223

**Comment by cxj** [comment]
Sorry about the testing error.  "My bad."  Will have PR to fix shortly.

**Comment by harikt** [comment]
no problem @cxj . We need to fix it though. Either via not getting from ini or something else.

**Comment by cxj** [comment]
Hmm.  I don't understand how Travis is functioning to produce these errors.  When I run PHPUnit from the command line, the tests all pass.

**Comment by harikt** [comment]
@cxj you can look at your php.ini value for `gc_maxlifetime`  or execute below in cli.

```
php -r "echo ini_get('session.gc_maxlifetime');"
```

Your `gc_maxlifetime` will be greater than the default one 1440.

Let me know if I am wrong.

**Comment by cxj** [comment]
Yes, I know that.  The default that Travis is using is a poor value, and an unreliable way to test.  Please see my comments under PR #89.

**Pull request merged**
