### PR TITLE
Fix meaningful timeout values patch.

### PR DESCRIPTION
**Pull request by cxj**
My PR #84 was an incomplete fix for issue #81.  Two other source changes need to get the same better timeout values.  And the 2 unit tests which test that code also need to be updated.  This commit fixes those problems.  My apologies.

### CODE REVIEW

**Comment by cxj** [comment]
The problem appears to be the value set for `gc_maxlifetime` in the Travis `php.ini` file.

It seems ultra-fragile to depend upon reasonable values in someone else's `php.ini` file to have a unit test work correctly.

We could create a custom PHP config file [per this Travis documentation](https://docs.travis-ci.com/user/languages/php/#Custom-PHP-configuration).  Is that perhaps the correct solution?

**Comment by cxj** [comment]
Alternatively, we could do one of the following.

1. Add this to `phpunit.xml.dist`:
```xml
<php>
    <ini name="session.gc_maxlifetime" value="86400"/>
</php>
```

2. Add `ini_set()` to `AuthFactoryTest.php`:
```php
@@ -13,6 +13,7 @@ class AuthFactoryTest extends \PHPUnit_Framework_TestCase
     protected function setUp()
     {
         $this->factory = new AuthFactory($_COOKIE);
         ini_set("session.gc_maxlifetime", 86400) or die("cannot ini_set");
     }
```

**Comment by cxj** [comment]
I've gone with the PHPUnit XML file fix as the best choice at this point.

**Comment by Qrzysio** [comment]
Hopefully, we can get a new release with fixed  `idle_ttl` and `expire_ttl` values, as the default is still like this:
```
            'idle_ttl' => 1440,
            'expire_ttl' => 14400,
```

**Comment by Qrzysio** [comment]
Why not add other methods which will allow users to get/set  `session.gc_maxlifetime`? 
Something like this:

```
public function setGCmaxlifetime($value)
{
    if (ini_set("session.gc_maxlifetime", $value) === false) {
        throw new Exception('Cannot set session.gc_maxlifetime');
    }
}

public function getGCmaxlifetime()
{
    return ini_get('session.gc_maxlifetime');
}

```

**Comment by cxj** [comment]
This is fixed in the 4.x branch and release 4.0.0.  The 2.x branch is quite out dated by now, so I am closing this PR.

**Pull request closed without merging**
